# Generated by Django 5.1.3 on 2024-11-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
